### ISSUE TITLE
Incorrect documentation with version numbers

### ISSUE THREAD

**Issue by ProjectPatatoe** [makerbase-mks/MKS-Robin-Nano-V3.X#13]
hardware/MKS Robin Nano V3.0_003 doesn't all the correct documentation for it's version.

Version 001
* Bottom - correct
* Pin - correct
* Sch - correct
* Size - correct
* Top - correct

Version 002
* Bottom - correct
* Pin - correct
* Sch - correct
* Size - correct
* Top - correct

Version 003
* Bottom - correct
* Pin - incorrect, shows version 2
* Sch - incorrect, shows version 2
* Size - incorrect, shows version 2
* Top - incorrect, shows version 2

**Comment by mks-viva** [comment]
Thank you, i will fix it

**Comment by mks-viva** [comment]
I has fix it
