### ISSUE TITLE
Mismatched fan pin on documentation

### ISSUE THREAD

**Issue by ProjectPatatoe** [makerbase-mks/MKS-Robin-Nano-V3.X#14]
all revisions (001-003) has mismatched pin outs for Fan1 and Fan2. which is correct? It seems like the pin out got swapped between the FAN1 tag and the actual circuit/jack intended.

Images below are from 002 but the same or similar mismatch is on 001 and 003

* 002 BOTTOM.pdf
![image](https://user-images.githubusercontent.com/27925441/111884198-39e29500-897d-11eb-84f3-45b1820fa060.png)
* 002 PIN.pdf
![image](https://user-images.githubusercontent.com/27925441/111884203-42d36680-897d-11eb-9470-55acf887d0e3.png)
* 002 SCH.pdf
![image](https://user-images.githubusercontent.com/27925441/111884225-71e9d800-897d-11eb-8345-2f684c63cd0c.png)

![image](https://user-images.githubusercontent.com/27925441/111884257-a5c4fd80-897d-11eb-98f7-dfee153af8d9.png)
* 002 SIZE.pdf
![image](https://user-images.githubusercontent.com/27925441/111884270-b7a6a080-897d-11eb-9f07-395747a40645.png)
* 002 TOP.pdf
![image](https://user-images.githubusercontent.com/27925441/111884277-ce4cf780-897d-11eb-867b-eebc94cb164d.png)

**Comment by mks-viva** [comment]
PC14 use for FAN1
PB1 use for FAN2
We fix it

**Comment by mks-viva** [comment]
In the latest version 003 PCB, we have modified it 
![image](https://user-images.githubusercontent.com/16629551/111928295-21de5300-8aee-11eb-8784-91fb270e1356.png)

**Comment by ProjectPatatoe** [comment]
I ask for a clarification/fix because for 001 and 002 is because people who have an older revision board can't be sure what exactly they are seeing.

In addition, 003 still has inconsistencies. Specifically on the SCH sheet, they go to different connectors
* 003 BOTTOM.pdf
![image](https://user-images.githubusercontent.com/27925441/111928604-5829bd00-8a71-11eb-8d43-b4f7a828ffec.png)
* 003 PIN.pdf
![image](https://user-images.githubusercontent.com/27925441/111928620-64157f00-8a71-11eb-8d76-2df03795bcf6.png)
* 003 SCH.pdf
![image](https://user-images.githubusercontent.com/27925441/111928635-75f72200-8a71-11eb-9f15-752ee98644fb.png)
* 003 SIZE.pdf
![image](https://user-images.githubusercontent.com/27925441/111928657-7ee7f380-8a71-11eb-96bc-bd8e89b0a15c.png)
* 003 TOP.pdf
![image](https://user-images.githubusercontent.com/27925441/111928684-932bf080-8a71-11eb-9b2c-f0a7f791c85f.png)

**Comment by themacboy** [comment]
Why all this revisions? there are manofacturing or design problems in revisiopn 1 and 2? Why must request a board update (change)?

**Comment by mks-viva** [comment]
001 and 002 is design problems, so, we will fix it on 003 version

**Comment by ProjectPatatoe** [comment]
All (001-003) versions have documentation that is not reflecting what people have, making diagnosing or tracking errors difficult. For instance, these are the full list of differences I can see from manually comparing all of the sheets. Which really this should have been just listed somewhere!

Revision1vs2

 - fixed silkscreen for "E0_MOTOR" (Bottom sheet)
 - missing TH1 silkscreen (Pin sheet)
 - add a diode array / resistor bottom right by J55 (Pin sheet)
 - reworded/rearrange heater page (Sch sheet)
 - added diode protection on BLTouch (Sch sheet)
 - added 100ohm on BLTouch servo pin (Sch sheet)
 - a few more measurements (Size sheet)


Revision2vs3

 - fan pin switch (Bottom sheet)
 - <del>clarified resist/silk/copper layers (Bottom sheet)</del> recent changed undid this ):

**Comment by mks-viva** [comment]
001 and 002 is has silkscreen error and the actual PCB also has the same silk screen error, so this cannot be modified 
003 has fix all the silkscreen error and i has update sch

**Comment by ProjectPatatoe** [comment]
Ok so those pin notations are actual silk screens and not just notes? its hard to tell because everything is the same color. Perhaps a note should be put next to it as someone diagnosing their board wouldn't know that its an error

**Comment by mks-viva** [comment]
just like what you said, those pin notations are actual silk screens and not just notes. So, 003 version hardware has fix it.

**Comment by ProjectPatatoe** [comment]
OK since its now relatively documented both here as well in the updated documents and readme, I will close the issue.
