### ISSUE TITLE
Please update wiki about MKS Robin Nano and MKS PWC.

### ISSUE THREAD

**Issue by kad** [makerbase-mks/MKS-Robin-Nano-V3.X#15]
Currently wiki for using PWC and Nano 3.x doesn't have needed information about firmware settings and wire connections informations.

**Comment by mks-viva** [comment]
We will update it

**Comment by anthorid13** [comment]
MKS PWC ne fonctionne pas avec marlin 2.0.8.1. pouvez vous mettre à jour le fichier pin du robin nano v3

**Comment by mks-viva** [comment]
The leatest marlin has fix it.
