### ISSUE TITLE
PD15 for XDIAG and E1 step in MKS Robin Nano V3.0_003 PIN.pdf

### ISSUE THREAD

**Issue by WonderRat** [makerbase-mks/MKS-Robin-Nano-V3.X#17]
Must be "PA15" for XDIAG?

Also how about renaming "IO1" to "WIFI_IO4" (PC7)?

**Comment by mks-viva** [comment]
![image](https://user-images.githubusercontent.com/16629551/114387119-a7709280-9bc4-11eb-8a72-6c03a4c0831d.png)

**Comment by WonderRat** [comment]
![20210412002](https://user-images.githubusercontent.com/17234818/114390050-307ccf00-9baf-11eb-8d0c-97aa86b79e93.png)

**Comment by mks-viva** [comment]
I need to check it, it may be wrong pin labeling, thank you for your feedback
