### ISSUE TITLE
Virtual USB feature 

### ISSUE THREAD

**Issue by Ainmimdal** [makerbase-mks/MKS-Robin-Nano-V3.X#18]
Somehow I can't get my computer to detect any storage devices when connected to the board via USB. I already changed the default environment in platform io to mks_robin_nano_v3_msc. I compiled my firmware using Auto Build Marlin but it only has two environments: mks_robin_nano_v3 and mks_robin_nano_v3_usb. I tried building mks_robin_nano_v3_usb_flash_drive_msc directly from platformio but the board keeps resetting when using USB. There are also no storage devices detected. Am I missing anything?

**Comment by spammchik** [comment]
> Somehow I can't get my computer to detect any storage devices when connected to the board via USB. 

Hello. How could you fix this?

**Comment by 123Li220** [comment]
> Somehow I can't get my computer to detect any storage devices when connected to the board via USB. 
Hi, I do have the same issue. Could you post here how you solved it?

**Comment by Ainmimdal** [comment]
Sorry everyone I had a long break from 3d printing but if anyone still have this issue, I just cloned the freshest copy of the firmware and build using platformio using the msc environment. The usb data transfer works but very unreliable (loses connection and hangs my file explorer) that I never bothered to even try using anymore
