### ISSUE TITLE
Endstop not work

### ISSUE THREAD

**Issue by alfaxx83** [makerbase-mks/MKS-Robin-Nano-V3.X#19]
Endstop not work

**Comment by mks-viva** [comment]
Please add more information about "Endstop not work"

**Comment by Jugin88** [comment]
hi, I'm new to the subject, my endstops don't work either, no matter what the pin assignment is, don't want to stop.

**Comment by mks-viva** [comment]
@Jugin88 
1. Check endstop hardware is OK?
2. You need set endstop false or ture in configuration.h file

**Comment by alfaxx83** [comment]
True or false change does not work. I endstop with LEDs. I have a printer Flying Bear Ghost 5

**Comment by mks-viva** [comment]
Usually, endstop's S G connect to board's S G, you need change endstop logic in configuration.h file when homing have not stop.

**Comment by lowtolerance** [comment]
If you follow the configuration check in the documentation, you should be able to resolve this problem on your own. You probably just  need to enable a pull-up or invert the logic, but klipper provides the tools for testing endstop functionality without actually attempting to home the axis.

**Comment by nfalco79** [comment]
I have the same issue and seems no configuration will resolve the issue. I have Flybear Ghost5, I had buy a Robin Nano 3.1. All endstops are ignored and the head try go over
