### ISSUE TITLE
EEprom datasize error

### ISSUE THREAD

**Issue by Dtcreation** [makerbase-mks/MKS-Robin-Nano-V3.X#20]
Hi,

I can't save my settings in the eeprom, i've got this message : eeprom datasize error

What can i do ?

Thanks

**Comment by mks-viva** [comment]
What command did you send?

**Comment by Dtcreation** [comment]
M500

**Comment by mks-viva** [comment]
Can you provide your firmware sourcode to me? I need rebuild it and test it.

**Comment by Dtcreation** [comment]
Hello,
Here the sourcecode. 

https://github.com/Dtcreation/Firmware-Molise-Artillery/tree/compil_hex

Can you confim me that there is no eeprom on the mainboard ?

Thanks

**Comment by mks-viva** [comment]
I has test it and it's has error, you can use https://github.com/makerbase-mks/Mks-Robin-Nano-Marlin2.0-Firmware path firmware and it's ok.

**Comment by Dtcreation** [comment]
Hi,
I found the problem.
Thanks
