### ISSUE TITLE
Alternative bootloader for REPRAP firmware

### ISSUE THREAD

**Issue by Lino77** [makerbase-mks/MKS-Robin-Nano-V3.X#22]
Is it possible to provide the bootloader code, which it can be adapted for the reprap firmware, or to provide a compatible one

**Comment by WonderRat** [comment]
I suspect that reducing bootloader and flashing firmware at 0x8008000 will be enough.

**Comment by Lino77** [comment]
240 / 5000
Übersetzungsergebnisse
the bootloader expect the firmware to be encrypted so I want an alternative bootloader that can be loaded onto the firmware without encrypting the bin file. best that you expect firmware.bin like everyone else

**Comment by whhx-open** [comment]
The boot program of nano v3 has not encrypted the bin file.
The startup offset address of nano v3 is 0x800c000. I tried to modify the ldscript.ld file on rrf to adapt to nano v3, but the firmware after compiling rrf still cannot run on nano v3. I haven't found the reason yet.

**Comment by Lino77** [comment]
@whhx-open 
Take a look there 
https://discord.com/channels/461605380783472640/491165528295997450/835794924330418186

https://github.com/makerbase-mks/Software/tree/master/binEncode

**Comment by whhx-open** [comment]
The file encryption process is not included in the ini file, so there is no need for encryption.
![image](https://user-images.githubusercontent.com/14251428/116207397-6c4c9280-a772-11eb-834d-fe01ea4f0d98.png)

**Comment by Lino77** [comment]
you are right, but the board with the modified LDscript still does not boot

**Comment by mks-viva** [comment]
You can refer to here: https://github.com/makerbase-mks/RepRapFirmware-for-MKS-Boards
