### ISSUE TITLE
Pantalla TS35 V2 no enciende / not on

### ISSUE THREAD

**Issue by Souls-Reaver** [makerbase-mks/MKS-Robin-Nano-V3.X#25]
Hola!
tengo un problema, actualice el fimware de mi robin v3 con la pantalla classic, y funciono. Luego volvi a la LVGL y ya la pantalla nunca más encendio. He probado otras firmware, los que estan aqui subidos y compilados, dejo la placa base solo con la sd y la pantalla conectada, pero sigue igual. No enciende, ni pita, ni nada de nada. me podeis ayudar?

google translate

Hi!
i have a problem, i update my robin v3 fimware with classic screen, and it works. Then he went back to the LVGL and the screen never lit up again. I have tried other firmware, those that are uploaded and compiled here, I leave the motherboard only with the sd and the screen connected, but it remains the same. It does not turn on, or beeps, or anything at all. Can you help me?

**Comment by mks-viva** [comment]
Hi! You can try to use this link firmware update and check it. I think it is a firmware setting problem.
https://github.com/makerbase-mks/MKS-Robin-Nano-V3.X/tree/main/firmware/Marlin-bugfix2.0.x-MKS-2.1.2/Firmware%20bin%20for%20suport%20usb-disk
![image](https://user-images.githubusercontent.com/16629551/116663568-de6ae480-a9c9-11eb-9bc8-24cfeff25aa7.png)

**Comment by Souls-Reaver** [comment]
El problema fue que la electrónica estaba muerta.
