### ISSUE TITLE
Connecting to Octoprint.

### ISSUE THREAD

**Issue by dimitribizakis** [makerbase-mks/MKS-Robin-Nano-V3.X#30]
Trying to connect to octoprint, at first has connected successfully but after a firmware update cannot connect.
The usb at Raspberry Zero-w see's the USB device and tries to connect but it cannot execute the starting communication gcodes.
I have connected to PC and used Prontface with success.

**Comment by mks-viva** [comment]
Are you trying to restart all devices?

**Comment by dimitribizakis** [comment]
> Are you trying to restart all devices?

Offcourse, i ever reset both off them.
