### ISSUE TITLE
TS35

### ISSUE THREAD

**Issue by RunekcDK** [makerbase-mks/MKS-Robin-Nano-V3.X#31]
Hi, I have just changed my Nano 1.2 with TFT35 to a Nano V3 with TS35 but having a hard time getting the touch screen to work correctly. By default it works but for my setup I have to rotate the screen 180 degrees which is also fine but the issue is that the touch interface doesn't rotate with the screen so all the "buttons" are in the wrong place. I have tried all sorts of combinations but nothing works, is this a TS35 limitation or is it a Marlin limitation.

best regards

Rune

**Comment by lilive1372** [comment]
Hi,

you just have to activate this line
#define TOUCH_ORIENTATION TOUCH_LANDSCAPE

good luck

**Comment by RunekcDK** [comment]
Hi, thank you but that didn't do it, I had to send M995 to calibrate the touch screen, the old TFT35 did it after every firmware flash.

**Comment by mks-viva** [comment]
Now, you can update it to the latest version and test it.
