### ISSUE TITLE
dual z-stepper not working properly

### ISSUE THREAD

**Issue by Stockhauz** [makerbase-mks/MKS-Robin-Nano-V3.X#34]
i just installed a second z-stepper motor and connected it to E1 on the board (to utilize a second stepper driver).
But when moving the z axis down, the E1 (second Z motor) moves up.
When i issue command to move Z up both motors move up
But when i issue a command to move z down, Z1 motor moves down, Z2 motor moves up.

I tried switching the cable on the boards, but that only made Z1 have the problem instead (only moving up).

Have i missed something?
it seems like there is something off with the pins on E1?
pins_MKS_ROBIN_NANO_V3.h seems to correspond correctly with the hardware pin diagram.
#define E1_ENABLE_PIN                       PA3
#define E1_STEP_PIN                         PD15
#define E1_DIR_PIN                          PA1
#ifndef E1_CS_PIN
  #define E1_CS_PIN                         PD8
#endif

![image](https://user-images.githubusercontent.com/37406183/117324997-9d267900-ae90-11eb-9f4a-56934b76b0d4.png)
inclued my configuration files
[conf.zip](https://github.com/makerbase-mks/MKS-Robin-Nano-V3.X/files/6435924/conf.zip)

**Comment by Stockhauz** [comment]
I seem to have solved the issue by instead of using the official Marlin repo, i used MKS repo instead for Marlin.
Downloaded master branch, enabled stuff like dual z and ubl, and now it works.

**Comment by ysnuysl** [comment]
Hi, which version of marlin are you using? And can you tell me how you did what you mentioned? I am using the latest version marlin but the screen stays white.
