### ISSUE TITLE
Advanced settings on MKS Robin Nano v3.x

### ISSUE THREAD

**Issue by zrox86** [makerbase-mks/MKS-Robin-Nano-V3.X#35]
Is there a possibility to have advanced settings (machine settings (step, invert, ...) in the setting menu) on NR v3.x like on Nano Robin v1.x, to tweek the settings over the display

**Comment by makerbase-mks** [comment]
@zrox86 Actually, robin nano v3 has supported the advanced settings on TS35 , just like the menu of using LCD12864... What's your problem?

**Comment by easotokr** [comment]
I have similar problem, In LCD I can see even PIDTune but in my TS35 no

**Comment by Allidoisowen** [comment]
Same thing here. I would like to be able to have more options available on the TS35. I tried switching to the classic UI. More options were available, but the experience was not good. Back to the LVGL settings, but limited menu options.

**Comment by mks-viva** [comment]
Many parameters need to be recompiled to be effective. The original Nano V1.2 firmware has adjusted.
