### ISSUE TITLE
Disable beeper ...

### ISSUE THREAD

**Issue by themacboy** [makerbase-mks/MKS-Robin-Nano-V3.X#37]
Good morning,

It is possible to disable beeper? 

Thanks in advance!

**Comment by mks-viva** [comment]
Hi! The machine power on you said?

**Comment by themacboy** [comment]
Yes, por the beep after update or other beep

**Comment by mks-viva** [comment]
Ok! We will give the firmware and update method

**Comment by mks-viva** [comment]
https://github.com/makerbase-mks/MKS-Robin-Nano-V3.X/tree/main/bootloader/No%20beep
![Uploading image.png…]()

**Comment by iNDeX999** [comment]
After Updating my V§ "MKS-Robin-Nano-V3.X/bootloader/No beep/" and waiting till nothing happend anymore (100% shown for 10min) i rebooted the Board. The System still Beeps, but no Display working / USB dead, and now?!

**Comment by iNDeX999** [comment]
> https://github.com/makerbase-mks/MKS-Robin-Nano-V3.X/tree/main/bootloader/No%20beep
> ![image](https://user-images.githubusercontent.com/16629551/120180193-0c984a00-c23e-11eb-9e59-0ce4160114f7.png)

After Updating my V3 with the quite patch "MKS-Robin-Nano-V3.X/bootloader/No beep/" and waiting till nothing happend anymore (100% shown for 10min) i rebooted the Board.
The System still Beeps, but Display not working / USB dead, and now?!
