### ISSUE TITLE
RRF firmware for the new bootloader

### ISSUE THREAD

**Issue by Lino77** [makerbase-mks/MKS-Robin-Nano-V3.X#39]
[RRF.zip](https://github.com/makerbase-mks/MKS-Robin-Nano-V3.X/files/6602078/RRF.zip)

the original RRF firmware does not work because a few adjustments have to be made in the RRF for those who just want to test it,

**Comment by Zannys** [comment]
omg, i want to test rrf in this board since i realise the wifi module has spi connections, this version of rrf i need to reflash bootloader follow this tutorial?  https://github.com/makerbase-mks/MKS-Robin-Nano-V3.X/tree/main/bootloader/No%20beep

**Comment by Souls-Reaver** [comment]
Y que mejoras tiene esto?

**Comment by themacboy** [comment]
excuse me! It ispossible to use RepRap in this board? Who coded that?

**Comment by Zannys** [comment]
> excuse me! It ispossible to use RepRap in this board? Who coded that?

yes, i installed, but i not test yet, but is very promising
![image](https://user-images.githubusercontent.com/10759986/121231597-f3f3e980-c866-11eb-88fa-81e7db16aebf.png)

**Comment by themacboy** [comment]
> 
> 
> > excuse me! It ispossible to use RepRap in this board? Who coded that?
> 
> yes, i installed, but i not test yet, but is very promising
> ![image](https://user-images.githubusercontent.com/10759986/121231597-f3f3e980-c866-11eb-88fa-81e7db16aebf.png)

I will wait for a Official announcement. Thx for the effort !

**Comment by mks-viva** [comment]
MKS has add bootloader for nano v3 and support rrf firmware: https://github.com/makerbase-mks/RepRapFirmware-for-MKS-Boards
