### ISSUE TITLE
Does not read usb or micro sd help me..

### ISSUE THREAD

**Issue by gusalgora** [makerbase-mks/MKS-Robin-Nano-V3.X#42]
I have a problem with the MKS ROBIN NANO V3, update the BOARD with a 16GB micro SD by compiling MARLIN with visual studio code. I did this to be able to use the BL TOUCH and after that it does not read SD or USB cards, and I don't know how to install the original version, without the SD or USB, HELP.
I don't know how to fix it.
¿How can I fix it?

Components:
1 x Makerbase MKS Robin Nano V3 
5 x TMC2225
1 x Display TS35

**Comment by mks-viva** [comment]
Hi! You use the latest version marlin?

**Comment by mks-viva** [comment]
Is this issue resolved? If there is no response, I will temporarily close this issues.
