### ISSUE TITLE
Question about the max current output of the 5V regulator

### ISSUE THREAD

**Issue by luizete** [makerbase-mks/MKS-Robin-Nano-V3.X#52]
Hi, I would like to connect my Raspberry Pi directly to the 5V line of the Nano V3 motherboard, but I can't find the regulator specs.  How many mA can the regulator handle?
Thanks.

**Comment by mks-viva** [comment]
MKS Robin Nano V3 DC5V is use MP1584EN(5V/3A), but fuse is 1.5A, so, you can connect to board's 5V interface

**Comment by luizete** [comment]
Thank you very much!
