### ISSUE TITLE
SD Card and USB flash drive port disabled by mistake. I can't Flash

### ISSUE THREAD

**Issue by decasicko** [makerbase-mks/MKS-Robin-Nano-V3.X#53]
Hello there.

This is my first week with the MKKKS Robin Nano V3.0 board and i'm stucked.

I flash and re-flash Marlin firmware to put my printer configuration.

I thought it was well configured but by mistakke i kkept commented the line:

 //#define USB_FLASH_DRIVE_SUPPORT

Most of times i used the third option, so i could re-flash by SD card

![image](https://user-images.githubusercontent.com/89147659/129919518-8b3534c5-b67e-4e1a-b261-0c4863382ca7.png)

But the last time i used the middle option (Thinking it would solve my problem with USB).

So, right now, SD Card port and USB flash port are disabled so i can't reflash again to solve the problem.

Printer is working attached to Octoprint or Pronterface.

I tried the Upload button because plattform.io find the Serial COM port, but nothing happen.

Anybody can help me about how to solve it?

Thanks in advance!

**Comment by mks-viva** [comment]
If you need use board's TF card or Udisk function:
1. Use TF card
  - You only select **mks_robin_nano_v3** in platformio.ini file
  - You need enable **#define SDSUPPORT** in Configuration.h file

2. Use Udisk
  - You need select **mks_robin_nano_v3_usb_flash_drive** or **mks_robin_nano_v3_usb_flash_drive_msc** in platformio.ini file
  - You need enable **#define SDSUPPORT** in Configuration.h file
  - In Configuration_adv.h file: **#define USB_FLASH_DRIVE_SUPPORT**

**Comment by decasicko** [comment]
> If you need use board's TF card or Udisk function:
> 
> 1. Use TF card
> 
> * You only select **mks_robin_nano_v3** in platformio.ini file
> * You need enable **#define SDSUPPORT** in Configuration.h file
> 
> 1. Use Udisk
> 
> * You need select **mks_robin_nano_v3_usb_flash_drive** or **mks_robin_nano_v3_usb_flash_drive_msc** in platformio.ini file
> * You need enable **#define SDSUPPORT** in Configuration.h file
> * In Configuration_adv.h file: **#define USB_FLASH_DRIVE_SUPPORT**

Yes, i know (now)

But by mistake i flashed selecting mks_robin_nano_v3_usb_flash_drive
I enabled #define SDSUPPORT
But i didn't enable #define USB_FLASH_DRIVE_SUPPORT

So now SD port or USB flash disk port not working. If i put a new firmare on it and reboot, nothing happen.

So i am looking for a way to update firmare using USB serial port (Pronterface working in a lapton by conecting USB port and Octoprint aswell.)

**Comment by mks-viva** [comment]
Your idea is to download the firmware directly to the motherboard via USB?

**Comment by decasicko** [comment]
I don't know. My idea is to find out how to update firmware in the board if the SDCard and the USB Flash port are not working. (Because it's not enabled in firmware by mistake.

**Comment by mks-viva** [comment]
MKS Robin Nano V3 update firmware is very easy, you only copy Robin_nano_v3.bin to tf card and insert it to board, reset board and it's will update. You don’t need to consider marlin firmware settings, because the function of updating the firmware is implemented in the BootLoader program.

**Comment by decasicko** [comment]
So, my TF port is broken. Because it didn't flash Booting with the bin file in the TF CARD.

**Comment by mks-viva** [comment]
Usually, the TF card should be in FAT32 format, maybe you need to format it

**Comment by decasicko** [comment]
Done, sometimes, and tested with 2 different TF cards.

**Comment by decasicko** [comment]
SOLVED.


Forget it. Tested with some TF cards it was formatted in exFAT not FAT32.

I pick an old TF card, formatted in FAT32, reset printer and it UPDATE!


So we can close this Issue.

To everyone will come later, take note of thismks-viva comment:

"you only copy Robin_nano_v3.bin to tf card and insert it to board, reset board and it's will update. You don’t need to consider marlin firmware settings, because the function of updating the firmware is implemented in the BootLoader program.

 the TF card should be in FAT32 format"
