### ISSUE TITLE
Can't adjust the offset Z parameter 

### ISSUE THREAD

**Issue by DoctorDeatch** [makerbase-mks/MKS-Robin-Nano-V3.X#54]
Cannot adjust induction leveling sensor
the system does not allow the table to be moved to -Z
The set parameter is the offset of the Z EEPROM sensor (M851 Z xx), both negative and positive are ignored
how to overcome the problem?

**Comment by mks-viva** [comment]
https://github.com/makerbase-mks/Mks-Robin-Nano-Marlin2.0-Firmware/issues/273
So, i close this issues.
