### ISSUE TITLE
Help installing Klipper ...

### ISSUE THREAD

**Issue by themacboy** [makerbase-mks/MKS-Robin-Nano-V3.X#57]
Im looking for people with experience installing klipper in this board.

**Comment by mks-viva** [comment]
Refer to here: https://github.com/makerbase-mks/Klipper-for-MKS-Boards
![image](https://user-images.githubusercontent.com/16629551/133385176-76d52c1a-5118-45bd-9bf7-d6ddd20c87e9.png)

**Comment by themacboy** [comment]
WoW ! Missed that repository ! 

Lot of thanks ! Great work !

**Comment by poon-holder** [comment]
it is possible to boot klipper onto a debain distros buy using blanda to make a boot drive or is that not necessary? many thanks.
