### ISSUE TITLE
Robin Nano V3 rev 004 + display H43 + USB stick NOT start

### ISSUE THREAD

**Issue by spammchik** [makerbase-mks/MKS-Robin-Nano-V3.X#60]
Configuration: Robin Nano V3 rev 004 + display H43 V1.0 or V1.1 + USB stick
**Problem:** If you connect a USB drive to the Robin Nano V3 rev 004 and turn on the power via USB or 12V, **the electronics will not boot, display not work.**
Everything works fine without a USB stick.
If you plug in the USB stick after the electronics turn on, then everything works fine.
If there is no display H43, then the electronics starts with a USB drive fine.
This problem is not present on Robin Nano V3 rev 003.
**Question:** How to make the electronics Robin Nano V3 rev 004 + display H43 V1.0 or V1.1  boot and work with the USB drive connected?

**Comment by mks-viva** [comment]
Hi! I want to know, you use same the firmware on 003 and 004?

**Comment by spammchik** [comment]
The firmware is the same for 003 and 004.

**Comment by mks-viva** [comment]
004 hardware changes
![image](https://user-images.githubusercontent.com/16629551/135369214-ccd4a376-5c6b-4d4e-9f0a-eeb643915e78.png)

**Comment by KORSiRO** [comment]
Hi look this : https://github.com/makerbase-mks/MKS-Robin-Nano-V3.X/issues/76
I managed to find the solution after hours of testing;)
