### ISSUE TITLE
Problems with 12/24v 

### ISSUE THREAD

**Issue by leebrubaker** [makerbase-mks/MKS-Robin-Nano-V3.X#68]
I cannot seem to drive a fan with with the pwm fan outputs or either of the two 24volt output jacks on this board.  I can measure 24 volts at the output jacks and see the pwm waveform on an oscilloscope.  However, connecting these fan to my printer power supply drives them with no problems at all so I know they work. I've tried this with multiple fans, and cannot get one to work.  Is there some sort of current limiting occurring on this board?  If so, can you please tell me what type of fan will work?

**Comment by mks-viva** [comment]
I want to know:
1. Your FAN connect to FAN1 or FAN2?
2. If your send FAN's control cammand, the fan's led will light
FAN1: M106 P0 S255
FAN2: M106 P1 S255
