### ISSUE TITLE
How to enable serial 3 for octoprint comunication

### ISSUE THREAD

**Issue by easotokr** [makerbase-mks/MKS-Robin-Nano-V3.X#70]
Hello, 
          I can't connect the TX3, RX3 to communicate between raspberry pi and the board. It's possible to enable this serial so I can have serial and WIFI together?

**Comment by mks-viva** [comment]
You can set #define SERIAL_PORT_2  3 in Configuration.h file

**Comment by easotokr** [comment]
this disable the WIFI or not? just to be sure I won't use it
