### ISSUE TITLE
Cannot compile #warning "Motherboard DIAG jumpers must be removed when SENSORLESS_HOMING is disabled"

### ISSUE THREAD

**Issue by Bergateo** [makerbase-mks/MKS-Robin-Nano-V3.X#75]
This error, #warning "Motherboard DIAG jumpers must be removed when SENSORLESS_HOMING is disabled", is displayed when I try to compile and for this error I cannot create the .bin file to upload.

Anyone has any clue to solve this error?
My setup has:
- h43 screen
- TMC2208 in uart mode

**Comment by Bergateo** [comment]
Managed to solve it, it was compiling indeed but somehow the board didn't get the update

**Comment by jessepietila** [comment]
I get the warning as well---> "Motherboard DIAG jumpers must be removed when SENSORLESS_HOMING is disabled.

What to do?

**Comment by Romain80200** [comment]
Hello, you can ad that in configuration.h, line66:

//#define CUSTOM_VERSION_FILE Version.h // Path from the root directory (no quotes)
#define DIAG_JUMPERS_REMOVED
