### ISSUE TITLE
Gcode not visible on USB or SDcard

### ISSUE THREAD

**Issue by persival001** [makerbase-mks/MKS-Robin-Nano-V3.X#77]
Hello,

Since i have update my firmware with the lastest (by solawc 2.0.92), i can't see my Gcode files on my USB stick or SDcard, but, I can flash the firmware with USB.

Configuration.h
#define SDSUPPORT

Configuration_adv.h
#define USB_FLASH_DRIVE_SUPPORT

Thanks for your help

**Comment by mks-viva** [comment]
What you set env in platformio.ini file?

**Comment by persival001** [comment]
Hello mks-viva,

In platformio.ini i've set : default_envs = mks_robin_nano_v3_usb_flash_drive
Since my latest post, i've download the new firmware of solawc and eveything is ok ;)
