### ISSUE TITLE
Search does not work in PDF

### ISSUE THREAD

**Issue by WonderRat** [makerbase-mks/MKS-Robin-Nano-V3.X#9]
Open "MKS Robin Nano V3.0_003 SCH.pdf" in any viewer, press Ctrl-F and search something ("PC10" for example) - it not works.

**Comment by mks-viva** [comment]
Hi! I am very sorry, but the export of KICAD cannot be searched.

**Comment by WonderRat** [comment]
I found advice to use "plot" instead of "print": https://forum.kicad.info/t/kicad-pdf-copy-is-not-searchable/18081/3

**Comment by mks-viva** [comment]
Hi! I has update V3.0_003 SCH, you can search all the net
![Uploading image.png…]()
